databases:
  - name: live-polling-db
    databaseName: livepolling
    user: admin
    plan: free

services:
  # Backend Service
  - type: web
    name: live-polling-server
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install && npx prisma generate && npm run build
    startCommand: cd server && npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: live-polling-db
          property: connectionString

  # Frontend Service
  - type: web
    name: live-polling-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: live-polling-server
          property: host
