services:
  # Backend Service
  - type: web
    name: live-polling-server
    env: node
    region: singapore # Optional, choose closest
    plan: free
    buildCommand: cd server && npm install && npx prisma generate && npm run build
    startCommand: cd server && npm run start
    envVars:
      - key: PORT
        value: 10000
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: live-polling-db
          property: connectionString

  # Database Service
  - type: psql
    name: live-polling-db
    env: postgres
    plan: free # or starter
    databaseName: livepolling
    user: admin

  # Frontend Service
  - type: static
    name: live-polling-client
    env: static
    buildCommand: cd client && npm install && npm run build
    publishDir: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: live-polling-server
          property: url
